language: python
sudo: false
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.9-dev
install:
  - pip install -e .
  - pip install -U codecov coverage pytest pytest-cov
script: pytest --cov
after_success:
  - codecov
